version: 2.1

orbs:
  codecov: codecov/codecov@5

jobs:
  lint_and_test:
    docker:
      - image: python:3.10
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            pip install uv
            uv venv
            source .venv/bin/activate
            uv pip install -r requirements.txt
            uv pip install pytest-cov
            uv pip install flake8
            pip install -e .

      - run:
          name: Set PYTHONPATH
          command: |
            echo "export PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $BASH_ENV

      - run:
          name: Check Flake8 Installation
          command: |
            source .venv/bin/activate
            flake8 --version || echo "Flake8 is not installed!"

      - run:
          name: Run Flake8 Linting
          command: |
            source .venv/bin/activate
            mkdir -p lint-reports
            flake8 --output-file=lint-reports/flake8-report.txt || echo "Flake8 completed with warnings, but CI will continue."

      - store_artifacts:
          path: lint-reports/
          destination: flake8_reports

      - run:
          name: Run Ruff Linting
          command: |
            source .venv/bin/activate
            ruff check src/ tests/

      - run:
          name: Run Mypy Type Checking
          command: |
            source .venv/bin/activate
            mypy src/

      - run:
          name: Verify Tests Exist
          command: |
            source .venv/bin/activate
            pytest --collect-only

      - run:
          name: Run Tests with Coverage
          command: |
            source .venv/bin/activate
            pytest --cov=src --cov-report=xml --cov-report=html --junitxml=test-results/junit.xml

      - store_test_results:
          path: test-results/

      - store_artifacts:
          path: htmlcov/
          destination: coverage_html

      - store_artifacts:
          path: coverage.xml

      - codecov/upload

workflows:
  version: 2
  upload-to-codecov:
    jobs:
      - lint_and_test
      